const products = [
  {
    title: "Magnetite",
    category: ['Pop'],
    price: 89.0,
    img: "./assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: ['Samba', 'Baião', 'MPB'],
    price: 66.0,
    img: "./assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: ['Rock'],
    price: 50.0,
    img: "./assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: ['Soft Rock', 'Rock'],
    price: 22.0,
    img: "./assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
